#!/usr/bin/env bash
# Bring the KAINE Redis bus from a fresh clone to a healthy, authenticated,
# ping-able state in one invocation.
#
# - Generates a random password (or preserves the existing one with
#   --keep-password).
# - Writes compose/.env from scratch with exactly one
#   KAINE_REDIS_PASSWORD= line (no duplicate-key trap).
# - Mirrors the password into config/secrets.toml under [redis].password.
# - docker compose down && up -d so the container picks up the value.
# - Confirms the bus answers PING with PONG.
#
# Idempotent: re-running by default rotates the password. Use
# --keep-password when migrating between hosts or recovering after a
# config edit.
#
#   bash scripts/redis-bootstrap.sh
#   bash scripts/redis-bootstrap.sh --keep-password

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT="$(pwd)"

KEEP=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-password) KEEP=1; shift ;;
    --help|-h) sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

ENV_FILE="compose/.env"
SECRETS_FILE="config/secrets.toml"
SECRETS_EXAMPLE="config/secrets.example.toml"

# 1. Resolve the password.
PW=""
if [[ "$KEEP" -eq 1 && -f "$ENV_FILE" ]]; then
  PW=$(grep -E '^KAINE_REDIS_PASSWORD=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
  if [[ -z "$PW" || "$PW" == "replace-me-with-a-strong-random-password" ]]; then
    echo "==> --keep-password set but no usable existing password; generating new" >&2
    PW=""
  fi
fi
if [[ -z "$PW" ]]; then
  PW=$(openssl rand -hex 32)
  echo "==> generated a fresh random password"
else
  echo "==> preserving existing password from $ENV_FILE"
fi

# 2. Write compose/.env from scratch (no duplicate-key risk).
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/redis-bootstrap.sh. Single source of truth for the
# Redis password used by both compose/redis.yml and KAINE's bus client.
KAINE_REDIS_PASSWORD=$PW

# Optional: host-side port override if 6479 collides on this machine.
# Update config/kaine.toml [redis] port to match.
# KAINE_REDIS_HOST_PORT=6479
EOF
chmod 600 "$ENV_FILE"
echo "==> wrote $ENV_FILE (mode 600)"

# 3. Mirror into config/secrets.toml.
if [[ ! -f "$SECRETS_FILE" ]]; then
  cp "$SECRETS_EXAMPLE" "$SECRETS_FILE"
  echo "==> created $SECRETS_FILE from example"
fi
chmod 600 "$SECRETS_FILE"
# Replace the line `password = "..."` under [redis]. The example ships
# with a single quoted password value; the sed below matches any value.
if grep -qE '^password = ".*"' "$SECRETS_FILE"; then
  sed -i.bak -E "s|^password = \".*\"|password = \"$PW\"|" "$SECRETS_FILE"
  rm -f "${SECRETS_FILE}.bak"
else
  # No matching line — append under a [redis] section.
  if ! grep -q '^\[redis\]' "$SECRETS_FILE"; then
    printf '\n[redis]\n' >> "$SECRETS_FILE"
  fi
  printf 'password = "%s"\n' "$PW" >> "$SECRETS_FILE"
fi
echo "==> mirrored password into $SECRETS_FILE"

# 4. Recreate the container so the new password takes effect.
echo "==> docker compose -f compose/redis.yml down"
docker compose -f compose/redis.yml down --remove-orphans 2>&1 | sed 's/^/    /' || true
echo "==> docker compose -f compose/redis.yml up -d"
KAINE_REDIS_PASSWORD="$PW" docker compose -f compose/redis.yml up -d 2>&1 | sed 's/^/    /'

# 5. Wait for healthy, then ping.
echo -n "==> waiting for kaine-redis to be ready"
for i in $(seq 1 30); do
  if redis-cli -h 127.0.0.1 -p 6479 -a "$PW" --no-auth-warning ping 2>/dev/null | grep -q PONG; then
    echo " ok"
    break
  fi
  echo -n "."
  sleep 0.5
  if [[ "$i" -eq 30 ]]; then
    echo
    echo "==> timed out waiting for PONG; container logs:" >&2
    docker compose -f compose/redis.yml logs --tail=40 kaine-redis >&2
    exit 3
  fi
done

echo "==> kaine-redis is up at 127.0.0.1:6479 and authenticated"
echo "    password lives in $ENV_FILE (mode 600) and $SECRETS_FILE (mode 600)"
echo "    rotate later with: bash scripts/redis-bootstrap.sh"
