# SPDX-License-Identifier: LicenseRef-CAL-0.2
# Copyright (c) 2026 Kaine.One <kaine.one@tuta.com>

from __future__ import annotations

import asyncio
import logging
from dataclasses import asdict, fields, is_dataclass
from pathlib import Path
from typing import Any, ClassVar, Iterable, Optional

from kaine.bus.client import AsyncBus
from kaine.bus.schema import Event
from kaine.modules.base import BaseModule
from kaine.modules.praxis.audit_log import ActionAuditLog
from kaine.modules.praxis.effectors import (
    ActionRequest,
    ActionResult,
    Effector,
    FileWriteEffector,
    FileWriteRequest,
    NotifyEffector,
    NotifyRequest,
    ShellEffector,
    ShellRequest,
)
from kaine.modules.praxis.whitelist import CommandWhitelist
from kaine.security.intent_signing import verify_intent_signature
from kaine.workspace.volition import ACT, VOLITION_STREAM

log = logging.getLogger(__name__)

# Maps an effector name to the ActionRequest type the executive's `act` intent
# params are coerced into. Effectors only run for intents naming a known type.
_REQUEST_TYPES: dict[str, type[ActionRequest]] = {
    "file_write": FileWriteRequest,
    "notify": NotifyRequest,
    "shell": ShellRequest,
}


class Praxis(BaseModule):
    name: ClassVar[str] = "praxis"

    def __init__(
        self,
        bus: AsyncBus,
        *,
        sandbox_path: Path | str = "state/praxis/files",
        audit_log_path: Path | str = "state/praxis/audit.log",
        notification_command: str = "notify-send",
        notification_fallback_log: Path | str | None = "state/praxis/notifications.log",
        whitelist: Optional[CommandWhitelist] = None,
        enabled_effectors: Optional[Iterable[str]] = None,
        max_file_bytes: int = 1_048_576,
        baseline_salience: float = 0.3,
        alert_salience: float = 0.7,
        intent_stream: str = VOLITION_STREAM,
        intent_secret: Optional[bytes] = None,
        enforce_provenance: bool = True,
    ) -> None:
        super().__init__(bus)
        if not 0.0 <= baseline_salience <= 1.0:
            raise ValueError("baseline_salience must be in [0, 1]")
        if not 0.0 <= alert_salience <= 1.0:
            raise ValueError("alert_salience must be in [0, 1]")
        self._baseline_salience = float(baseline_salience)
        self._alert_salience = float(alert_salience)
        self._intent_stream = intent_stream
        self._intent_cursor = "0-0"
        self._audit = ActionAuditLog(audit_log_path)
        # Act-intent provenance boundary (Mechanism B). The per-boot HMAC secret
        # is generated by and held only in the cycle process and injected here
        # (and into Volition). `_handle_intent` verifies each act intent's
        # signature BEFORE constructing any request or running any effector, so a
        # forged/unsigned/replayed intent from a non-Volition writer is dropped.
        # `enforce_provenance` is True by default and FAILS CLOSED: enforcement
        # on with no secret rejects every act intent (a misconfigured boundary
        # must refuse to act, not silently pass). Setting it False is an explicit
        # opt-out used only to demonstrate a disabled boundary in the red-team
        # self-test — the harness must then detect the regression.
        self._intent_secret = intent_secret
        self._enforce_provenance = bool(enforce_provenance)
        # Replay guard — the highest realized seq per run_id. An act intent whose
        # seq is <= the high-water mark for its run_id is a replay and is
        # rejected. This is O(1) memory (not an unbounded set of realized pairs):
        #   * intents reach the replay check only AFTER signature verification, so
        #     every pair here was signed by THIS boot's IntentSigner — they all
        #     share one per-boot run_id (a forged run_id can't produce a valid
        #     HMAC), so the dict holds effectively one entry per boot;
        #   * seq is monotonic per run_id and Praxis reads act intents from a
        #     SINGLE ordered stream (volition.out) via one sequential loop, so a
        #     legitimate intent never arrives with a lower seq than one already
        #     realized — a high-water mark can never wrongly reject a legit intent
        #     and additionally rejects stale captures below the mark.
        # In-process (per-boot) guarantee: a full process restart rotates the
        # secret + run_id (old signatures fail verification outright), and a light
        # module restart preserves this instance state (see holds_external_resources
        # note in _verify_provenance). Durability across a HEAVY (externally
        # rebuilt) restart would need a persisted/rotating window — Praxis is not
        # a heavy module today.
        self._replay_high_water: dict[str, int] = {}
        # Effector-enablement whitelist (paper §3.4.4 / §3.5): the operator
        # decides which real-world effectors exist AT ALL. EMPTY by default — an
        # act intent naming an effector outside this set is blocked at the action
        # boundary and audit-logged, BEFORE the effector runs. This is the first
        # of two layers; the within-effector bounds (shell CommandWhitelist, file
        # sandbox) are the second. No effector — notify included — bypasses it.
        self._enabled_effectors: frozenset[str] = frozenset(enabled_effectors or ())
        self._effectors: dict[str, Effector] = {}
        self._effectors["file_write"] = FileWriteEffector(
            sandbox_path=sandbox_path, max_bytes=max_file_bytes
        )
        self._effectors["notify"] = NotifyEffector(
            notification_command=notification_command,
            fallback_log_path=notification_fallback_log,
        )
        self._effectors["shell"] = ShellEffector(whitelist or CommandWhitelist())

    @property
    def audit_log(self) -> ActionAuditLog:
        return self._audit

    @property
    def effectors(self) -> dict[str, Effector]:
        return dict(self._effectors)

    @property
    def enabled_effectors(self) -> frozenset[str]:
        """The operator-enabled effector whitelist (empty = nothing permitted)."""
        return self._enabled_effectors

    def register_effector(self, effector: Effector) -> None:
        self._effectors[effector.name] = effector

    async def initialize(self) -> None:
        # Seek to the latest intent entry so we only realize intents formed
        # after boot, mirroring Audio Out's dedicated-loop cursor seeding.
        try:
            latest = await self._bus.client.xrevrange(self._intent_stream, count=1)
        except Exception:
            latest = []
        if latest:
            entry_id = latest[0][0]
            if isinstance(entry_id, bytes):
                entry_id = entry_id.decode()
            self._intent_cursor = entry_id
        await super().initialize()
        self._tasks.append(
            asyncio.create_task(self._intent_loop(), name=f"{self.name}-intent")
        )

    async def _intent_loop(self) -> None:
        """Realize `act` intents off ``volition.out``.

        Praxis is intent-driven: it never acts on the raw workspace broadcast.
        The only path to effector execution is an `act` intent from the
        executive action-selection step (which is gated by inhibition), so an
        inhibited entity performs no effector actions.
        """
        try:
            while not self._stopped.is_set():
                try:
                    entries = await self._bus.read(
                        self._intent_stream,
                        last_id=self._intent_cursor,
                        count=32,
                        block_ms=0,
                    )
                except Exception:
                    await asyncio.sleep(0.05)
                    continue
                if entries:
                    self._intent_cursor = entries[-1][0]
                    for _, event in entries:
                        await self._handle_intent(event)
                else:
                    await asyncio.sleep(0.05)
        except asyncio.CancelledError:
            raise

    async def _handle_intent(self, event: Event) -> None:
        if str(event.payload.get("kind") or "") != ACT:
            return
        # Provenance boundary — verified BEFORE any effector name is read, any
        # request is constructed, or act() is called. A missing/invalid/replayed
        # signature drops the intent and audit-logs it under the distinct
        # provenance_rejected category; no effector runs.
        rejection = self._verify_provenance(event)
        if rejection is not None:
            await self._record_provenance_rejected(event, rejection)
            return
        effector_name = str(event.payload.get("effector") or "")
        if not effector_name:
            log.warning("dropping act intent with no effector named")
            return
        request_type = _REQUEST_TYPES.get(effector_name)
        if request_type is None:
            log.warning("dropping act intent for unknown effector %r", effector_name)
            return
        params = event.payload.get("params") or {}
        try:
            request = request_type(**params)
        except Exception:
            log.exception(
                "act intent params do not match %s request shape", effector_name
            )
            return
        try:
            await self.act(effector_name, request)
        except Exception:
            log.exception("praxis failed to realize act intent for %s", effector_name)

    def _verify_provenance(self, event: Event) -> Optional[str]:
        """Return a rejection reason for an act intent, or ``None`` to accept.

        Accepts only an intent whose HMAC signature over
        ``canonical(kind, effector, params, run_id, seq)`` matches the per-boot
        secret AND whose ``(run_id, seq)`` pair has not been realized before. The
        reason strings are generic (no secret, signature, or payload content) so
        they are safe to audit-log. On acceptance the pair is recorded so a
        re-delivery of the same signed intent is rejected as a replay.
        """
        if not self._enforce_provenance:
            # Explicit opt-out: the disabled boundary. Only the red-team self-test
            # wires this; the harness must detect that forged intents now execute.
            return None
        if self._intent_secret is None:
            # Fail closed: enforcement is on but no secret was injected, so we
            # cannot verify anything — refuse to act rather than pass silently.
            return "provenance enforcement enabled but no signing secret configured"
        payload = event.payload
        signature = payload.get("sig")
        run_id = payload.get("run_id")
        seq = payload.get("seq")
        if not isinstance(signature, str) or not signature:
            return "act intent missing provenance signature"
        if not isinstance(run_id, str) or not run_id:
            return "act intent missing run_id"
        if not isinstance(seq, int) or isinstance(seq, bool):
            return "act intent missing or malformed seq"
        ok = verify_intent_signature(
            self._intent_secret,
            kind=ACT,
            effector=str(payload.get("effector") or ""),
            params=payload.get("params") or {},
            run_id=run_id,
            seq=seq,
            signature=signature,
        )
        if not ok:
            return "act intent signature is invalid"
        # Replay guard (see _replay_high_water in __init__). Rejects any seq at or
        # below the high-water mark for this run_id — the exact duplicate of a
        # realized intent AND any stale capture below the mark. Durability note:
        # this survives a LIGHT module restart because Praxis does not override
        # holds_external_resources() (defaults False), so Spot re-initializes THIS
        # instance rather than rebuilding a fresh one. If Praxis ever becomes a
        # heavy/externally-restarted module, revisit replay durability.
        prev = self._replay_high_water.get(run_id)
        if prev is not None and seq <= prev:
            return "act intent already realized (replay)"
        self._replay_high_water[run_id] = seq
        return None

    async def _record_provenance_rejected(self, event: Event, reason: str) -> None:
        """Audit + publish a provenance-rejected intent as METADATA ONLY.

        Logs the effector name (metadata, already logged for every action) and
        the generic reason — never the signature, the secret, or the intent's
        params/content. Distinct from a whitelist ``blocked`` refusal.
        """
        effector_name = str(event.payload.get("effector") or "")
        log.warning(
            "dropping act intent at the provenance boundary (%s); no effector runs",
            reason,
        )
        try:
            self._audit.append(
                effector=effector_name,
                request_summary={},
                success=False,
                elapsed_ms=0.0,
                error=reason,
                provenance_rejected=True,
            )
        except Exception:
            log.exception("praxis audit log append failed")
        await self.publish(
            "praxis.action",
            {
                "effector": effector_name,
                "success": False,
                "elapsed_ms": 0.0,
                "error": reason,
                "blocked": False,
                "provenance_rejected": True,
            },
            salience=self._alert_salience,
        )

    async def act(self, effector_name: str, request: ActionRequest) -> ActionResult:
        # Layer 1 — operator effector-enablement whitelist (empty by default).
        # Any effector not explicitly enabled by the operator is BLOCKED here,
        # before it can run, and audit-logged as a blocked action. This is
        # uniform: notify, file_write, shell, and any registered effector all
        # pass through this single gate — none is special-cased.
        if effector_name not in self._enabled_effectors:
            result = ActionResult(
                success=False,
                elapsed_ms=0.0,
                error=(
                    f"effector {effector_name!r} is not in the operator effector "
                    f"whitelist (blocked)"
                ),
            )
            await self._record(effector_name, request, result, blocked=True)
            return result
        effector = self._effectors.get(effector_name)
        if effector is None:
            result = ActionResult(
                success=False,
                elapsed_ms=0.0,
                error=f"unknown effector {effector_name!r}",
            )
            await self._record(effector_name, request, result)
            return result
        # Layer 2 — the effector's own within-bounds enforcement (shell
        # CommandWhitelist, file sandbox) runs inside effector.act.
        result = await effector.act(request)
        await self._record(effector_name, request, result)
        return result

    async def _record(
        self,
        effector_name: str,
        request: ActionRequest,
        result: ActionResult,
        *,
        blocked: bool = False,
    ) -> None:
        request_summary = _summarize_request(request)
        try:
            self._audit.append(
                effector=effector_name,
                request_summary=request_summary,
                success=result.success,
                elapsed_ms=result.elapsed_ms,
                error=result.error,
                blocked=blocked,
            )
        except Exception:
            log.exception("praxis audit log append failed")
        salience = self._baseline_salience if result.success else self._alert_salience
        await self.publish(
            "praxis.action",
            {
                "effector": effector_name,
                "success": result.success,
                "elapsed_ms": result.elapsed_ms,
                "error": result.error,
                "blocked": blocked,
            },
            salience=salience,
        )

    def serialize(self) -> dict[str, Any]:
        return {"effectors": sorted(self._effectors.keys())}

    def deserialize(self, state: dict[str, Any]) -> None:
        return


def _summarize_request(request: ActionRequest) -> dict[str, Any]:
    """Return a request shape minus its content payload."""
    if not is_dataclass(request):
        return {}
    out: dict[str, Any] = {}
    for f in fields(request):
        if f.name in ("content", "body", "stdout"):
            continue
        value = getattr(request, f.name)
        if isinstance(value, list):
            out[f.name] = list(value)
        else:
            out[f.name] = value
    return out
